[package]
name = "rruler"
version = "0.1.0"
edition = "2021"
authors = ["kbalt"]

[dependencies]
chrono = "0.4"
chrono-tz = "0.6"
nom = "7"
thiserror = "1"

[dev-dependencies]
pretty_assertions = "1"

rrule = "0.7"
itertools = "0.10"
